services:
  web:
    build:
      args:
        APP_ENV: dev
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - PHP_XDEBUG_ENABLED=1
      - PHP_INI_XDEBUG__CLIENT_PORT=9003
      - XDEBUG_CONFIG=client_host=host.docker.internal
      - PHP_IDE_CONFIG=serverName=smuldieet
    volumes:
      - .:/var/www/html
  database:
    ports:
      - ${DB_PORT}:${DB_PORT}
