services:
  web:
    build:
      args:
        APP_ENV: prod
    volumes:
      - uploadsPublic:/var/www/html/public/uploads
      - ./public/.well-known/acme-challenge:/var/www/html/public/.well-known/acme-challenge
    restart: always
  database:
    restart: always

volumes:
  uploadsPublic:
    driver: local
